In [5]:
import pandas as pd

In [8]:
data = pd.read_csv('gis.dukcapil.kemendagri.xlsx - Batas Desa.csv')

In [11]:
print(len(data['nama_prop'].unique()))

39

In [12]:
(data['nama_prop'].unique())

array(['JAWA TENGAH', 'ACEH', 'SULAWESI SELATAN', 'JAWA TIMUR',
       'SUMATERA UTARA', 'PAPUA PEGUNUNGAN', 'RIAU', 'SUMATERA BARAT',
       'SULAWESI TENGGARA', 'PAPUA', nan, 'JAWA BARAT', 'SULAWESI UTARA',
       'SULAWESI TENGAH', 'LAMPUNG', 'BANTEN', 'NUSA TENGGARA TIMUR',
       'PAPUA TENGAH', 'PAPUA BARAT DAYA', 'PAPUA BARAT',
       'KALIMANTAN BARAT', 'GORONTALO', 'NUSA TENGGARA BARAT',
       'PAPUA SELATAN', 'JAMBI', 'KALIMANTAN TIMUR', 'SUMATERA SELATAN',
       'MALUKU', 'KALIMANTAN SELATAN', 'SULAWESI BARAT', 'BENGKULU',
       'KALIMANTAN TENGAH', 'BALI', 'MALUKU UTARA', 'KALIMANTAN UTARA',
       'DAERAH ISTIMEWA YOGYAKARTA', 'DKI JAKARTA', 'KEPULAUAN RIAU',
       'KEPULAUAN BANGKA BELITUNG'], dtype=object)

In [13]:
data

,objectid,no_prop,no_kab,no_kec,no_kel,kode_desa_spatial,nama_prop,nama_kab,nama_kec,nama_kel,...,pensiunan,mengurus_rumah_tangga,perdagangan,perawat,nelayan,pelajar_mahasiswa,guru,wiraswasta,pengacara,lainnya
0,1335825,33.0,3.0,5.0,1012.0,3.303051e+09,JAWA TENGAH,KAB. PURBALINGGA,PURBALINGGA,KEMBARAN KULON,...,92.0,552.0,58.0,11.0,1.0,1014.0,45.0,634.0,1.0,NaN
1,1335826,11.0,1.0,1.0,2001.0,1.101012e+09,ACEH,KAB. ACEH SELATAN,BAKONGAN,KEUDE BAKONGAN,...,17.0,226.0,1.0,1.0,24.0,334.0,18.0,42.0,NaN,NaN
2,1335827,11.0,1.0,2.0,2009.0,1.101022e+09,ACEH,KAB. ACEH SELATAN,KLUET UTARA,PULO KAMBING,...,3.0,242.0,NaN,1.0,NaN,302.0,4.0,3.0,NaN,NaN
3,1335828,73.0,12.0,6.0,2002.0,7.312062e+09,SULAWESI SELATAN,KAB. SOPPENG,DONRI DONRI,DONRI DONRI,...,59.0,635.0,15.0,1.0,1.0,600.0,24.0,374.0,NaN,NaN
4,1335829,11.0,2.0,4.0,2011.0,1.102042e+09,ACEH,KAB. ACEH TENGGARA,BABUSSALAM,KAMPUNG MELAYU GABUNGAN,...,2.0,73.0,1.0,NaN,NaN,112.0,7.0,39.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83484,1419309,75.0,1.0,11.0,2025.0,7.501112e+09,GORONTALO,KAB. GORONTALO,BONGOMEME,KAYUMERAH,...,NaN,281.0,NaN,NaN,NaN,134.0,1.0,7.0,NaN,NaN
83485,1419310,75.0,1.0,11.0,2013.0,7.501112e+09,GORONTALO,KAB. GORONTALO,BONGOMEME,BATULAYAR,...,1.0,528.0,NaN,2.0,3.0,281.0,NaN,15.0,NaN,NaN
83486,1419311,75.0,1.0,4.0,2003.0,7.501042e+09,GORONTALO,KAB. GORONTALO,TIBAWA,DATAHU,...,30.0,1147.0,8.0,2.0,4.0,1088.0,16.0,247.0,NaN,NaN
83487,1419312,75.0,1.0,4.0,2001.0,7.501042e+09,GORONTALO,KAB. GORONTALO,TIBAWA,ISIMU UTARA,...,15.0,644.0,4.0,NaN,1.0,386.0,8.0,57.0,NaN,NaN
83488,1419313,75.0,1.0,9.0,2018.0,7.501092e+09,GORONTALO,KAB. GORONTALO,BOLIYOHUTO,DULOHUPA,...,3.0,146.0,2.0,3.0,4.0,156.0,9.0,23.0,NaN,NaN

In [18]:
df = data[data.notnull()]

In [27]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83489 entries, 0 to 83488
Columns: 104 entries, objectid to lainnya
dtypes: float64(99), int64(1), object(4)
memory usage: 66.2+ MB
None

In [21]:
df['nama_prop'].unique()

array(['JAWA TENGAH', 'ACEH', 'SULAWESI SELATAN', 'JAWA TIMUR',
       'SUMATERA UTARA', 'PAPUA PEGUNUNGAN', 'RIAU', 'SUMATERA BARAT',
       'SULAWESI TENGGARA', 'PAPUA', nan, 'JAWA BARAT', 'SULAWESI UTARA',
       'SULAWESI TENGAH', 'LAMPUNG', 'BANTEN', 'NUSA TENGGARA TIMUR',
       'PAPUA TENGAH', 'PAPUA BARAT DAYA', 'PAPUA BARAT',
       'KALIMANTAN BARAT', 'GORONTALO', 'NUSA TENGGARA BARAT',
       'PAPUA SELATAN', 'JAMBI', 'KALIMANTAN TIMUR', 'SUMATERA SELATAN',
       'MALUKU', 'KALIMANTAN SELATAN', 'SULAWESI BARAT', 'BENGKULU',
       'KALIMANTAN TENGAH', 'BALI', 'MALUKU UTARA', 'KALIMANTAN UTARA',
       'DAERAH ISTIMEWA YOGYAKARTA', 'DKI JAKARTA', 'KEPULAUAN RIAU',
       'KEPULAUAN BANGKA BELITUNG'], dtype=object)

In [30]:
bandung_df = df[df['nama_kab']=="KOTA BANDUNG"]

In [37]:
bandung_df.to_csv('bandung.csv')

In [ ]:
for index, row in bandung_df.iterrows():
    print(row.nama_kel ,row.nama_kec)

KARANG ANYAR ASTANA ANYAR
CIBADAK ASTANA ANYAR
PASTEUR SUKAJADI
PASIRLUYU REGOL
MARGASARI BUAHBATU
GARUDA ANDIR
PANJUNAN ASTANA ANYAR
CIHAPIT BANDUNG WETAN
ISOLA SUKASARI
SUKALUYU CIBEUNYING KALER
ANTAPANI KULON ANTAPANI
CISARANTEN BINA HARAPAN ARCAMANIK
BABAKAN BABAKAN CIPARAY
SUKAPURA KIARACONDONG
CISARANTEN KIDUL GEDEBAGE
CIKAWAO LENGKONG
KEBON PISANG SUMUR BANDUNG
SUKAHAJI BABAKAN CIPARAY
KARASAK ASTANA ANYAR
MARGAHAYU UTARA BABAKAN CIPARAY
KOPO BOJONGLOA KALER
NYENGSERET ASTANA ANYAR
JAMIKA BOJONGLOA KALER
BABAKAN ASIH BOJONGLOA KALER
MALEBER ANDIR
KEBON JERUK ANDIR
HUSEIN SASTRANEGARA CICENDO
PASIRKALIKI CICENDO
SUKARAJA CICENDO
SUKAWARNA SUKAJADI
SUKABUNGAH SUKAJADI
LEDENG CIDADAP
CIPAGANTI COBLONG
KEBON WARU BATUNUNGGAL
SARIJADI SUKASARI
LEBAK SILIWANGI COBLONG
CIATEUL REGOL
BALONG GEDE REGOL
GUMURUH BATUNUNGGAL
PALEDANG LENGKONG
CIJAGRA LENGKONG
CIBUNTU BANDUNG KULON
GEMPOL SARI BANDUNG KULON
MEKAR WANGI BOJONGLOA KIDUL
CIHAUR GEULIS CIBEUNYING KALER
BRAGA SUMUR BANDUNG
BATUNUNGGAL BANDUNG KIDUL
KUJANGSARI BANDUNG KIDUL
MANJAHLEGA RANCASARI
DERWATI RANCASARI
CIGENDING UJUNGBERUNG
CIPADUNG CIBIRU
PASANGGRAHAN UJUNGBERUNG
CIPADUNG KULON PANYILEUKAN
RANCANUMPANG GEDEBAGE
CIPADUNG WETAN PANYILEUKAN
PASIR IMPUN MANDALAJATI
KARANG PAMULANG MANDALAJATI
BABAKAN PENGHULU CINAMBO
CITARUM BANDUNG WETAN
CIKUTRA CIBEUNYING KIDUL
NEGLASARI CIBEUNYING KALER
PAJAJARAN CICENDO
PELINDUNG HEWAN ASTANA ANYAR
SEKELOA COBLONG
WARUNG MUNCANG BANDUNG KULON
SEKEJATI BUAHBATU
HEGARMANAH CIDADAP
CIBANGKONG BATUNUNGGAL
SITUSAEUR BOJONGLOA KIDUL
CIBADUYUT WETAN BOJONGLOA KIDUL
CIPADUNG KIDUL PANYILEUKAN
PASIR BIRU CIBIRU
PASIRJATI UJUNGBERUNG
RANCABOLANG GEDEBAGE
SAMOJA BATUNUNGGAL
CAMPAKA ANDIR
SUKAGALIH SUKAJADI
KACAPIRING BATUNUNGGAL
CIJERAH BANDUNG KULON
CIGONDEWAH RAHAYU BANDUNG KULON
BABAKAN SARI KIARACONDONG
ANTAPANI TENGAH ANTAPANI
ANTAPANI WETAN ANTAPANI
MEKAR MULYA PANYILEUKAN
MALABAR LENGKONG
PAMOYANAN CICENDO
CIGERELENG REGOL
LINGKAR SELATAN LENGKONG
BURANGRANG LENGKONG
CISARANTEN KULON ARCAMANIK
CIJAURA BUAHBATU
SUKAMULYA CINAMBO
CICADAS CIBEUNYING KIDUL
BABAKAN CIAMIS SUMUR BANDUNG
BABAKAN TAROGONG BOJONGLOA KALER
DUNGUS CARIANG ANDIR
ARJUNA CICENDO
GEGERKALONG SUKASARI
TURANGGA LENGKONG
CIMINCRANG GEDEBAGE
TAMAN SARI BANDUNG WETAN
CIBADUYUT BOJONGLOA KIDUL
CIRANGRANG BABAKAN CIPARAY
MERDEKA SUMUR BANDUNG
LEBAK GEDE COBLONG
DAGO COBLONG
KEBON JAYANTI KIARACONDONG
SUKAPADA CIBEUNYING KIDUL
SADANG SERANG COBLONG
MARGASUKA BABAKAN CIPARAY
CIROYOM ANDIR
ANCOL REGOL
CIBADUYUT KIDUL BOJONGLOA KIDUL
WATES BANDUNG KIDUL
PALASARI CIBIRU
CISARANTEN ENDAH ARCAMANIK
BABAKAN SURABAYA KIARACONDONG
KEBON KANGKUNG KIARACONDONG
BINONG BATUNUNGGAL
PADASUKA CIBEUNYING KIDUL
MEKARMULYA RANCASARI
MALEER BATUNUNGGAL
SUKA ASIH BOJONGLOA KALER
KEBON GEDANG BATUNUNGGAL
SUKAMISKIN ARCAMANIK
SINDANG JAYA MANDALAJATI
PASIRWANGI UJUNGBERUNG
PASIR ENDAH UJUNGBERUNG
PAKEMITAN CINAMBO
SUKARASA SUKASARI
PASIRLAYUNG CIBEUNYING KIDUL
CIPAMOKOLAN RANCASARI
CIGONDEWAH KALER BANDUNG KULON
CICAHEUM KIARACONDONG
CISURUPAN CIBIRU
CISARANTEN WETAN CINAMBO
MENGGER BANDUNG KIDUL
CIGONDEWAH KIDUL BANDUNG KULON
KEBON LEGA BOJONGLOA KIDUL
ANTAPANI KIDUL ANTAPANI
JATI SARI BUAHBATU
SUKAMAJU CIBEUNYING KIDUL
PUNGKUR REGOL
CARINGIN BANDUNG KULON
JATIHANDAP MANDALAJATI
BABAKAN CIPARAY BABAKAN CIPARAY
CISEUREUH REGOL
CIPEDES SUKAJADI
CIUMBULEUIT CIDADAP
CIGADUNG CIBEUNYING KALER

In [48]:
bandung_df.head(10).to_csv('t.csv')

In [49]:
bandung_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 151 entries, 4696 to 79335
Columns: 104 entries, objectid to lainnya
dtypes: float64(99), int64(1), object(4)
memory usage: 123.9+ KB

In [50]:
jakarta_df = df[df['nama_prop']=="DKI JAKARTA"]

In [51]:
jakarta_df

,objectid,no_prop,no_kab,no_kec,no_kel,kode_desa_spatial,nama_prop,nama_kab,nama_kec,nama_kel,...,pensiunan,mengurus_rumah_tangga,perdagangan,perawat,nelayan,pelajar_mahasiswa,guru,wiraswasta,pengacara,lainnya
4602,1340427,31.0,73.0,4.0,1006.0,3.173041e+09,DKI JAKARTA,KOTA ADM. JAKARTA BARAT,TAMBORA,JEMBATAN BESI,...,20.0,6792.0,3.0,6.0,1.0,8715.0,154.0,3309.0,1.0,NaN
6822,1342647,31.0,75.0,1.0,1001.0,3.175011e+09,DKI JAKARTA,KOTA ADM. JAKARTA TIMUR,MATRAMAN,PISANGAN BARU,...,271.0,7256.0,7.0,29.0,NaN,9714.0,304.0,2327.0,15.0,NaN
6827,1342652,31.0,74.0,1.0,1006.0,3.174011e+09,DKI JAKARTA,KOTA ADM. JAKARTA SELATAN,TEBET,MANGGARAI SELATAN,...,229.0,4797.0,5.0,22.0,NaN,6964.0,201.0,1874.0,3.0,NaN
6844,1342669,31.0,72.0,4.0,1007.0,3.172041e+09,DKI JAKARTA,KOTA ADM. JAKARTA UTARA,CILINCING,SEMPER BARAT,...,420.0,16345.0,5.0,190.0,4.0,21339.0,795.0,4488.0,18.0,NaN
6847,1342672,31.0,72.0,6.0,1001.0,3.172061e+09,DKI JAKARTA,KOTA ADM. JAKARTA UTARA,KELAPA GADING,KELAPA GADING TIMUR,...,1115.0,7350.0,4.0,22.0,NaN,8677.0,237.0,3166.0,25.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82294,1418119,31.0,74.0,8.0,1003.0,3.174081e+09,DKI JAKARTA,KOTA ADM. JAKARTA SELATAN,PANCORAN,RAWAJATI,...,260.0,3831.0,5.0,22.0,NaN,5961.0,161.0,1847.0,27.0,NaN
82295,1418120,31.0,74.0,9.0,1002.0,3.174091e+09,DKI JAKARTA,KOTA ADM. JAKARTA SELATAN,JAGAKARSA,SRENGSENG SAWAH,...,732.0,12763.0,8.0,143.0,1.0,19218.0,1002.0,3765.0,14.0,NaN
82296,1418121,31.0,74.0,10.0,1001.0,3.174101e+09,DKI JAKARTA,KOTA ADM. JAKARTA SELATAN,PESANGGRAHAN,PESANGGRAHAN,...,333.0,5574.0,6.0,62.0,NaN,9091.0,307.0,1874.0,19.0,NaN
82298,1418123,31.0,75.0,6.0,1001.0,3.175061e+09,DKI JAKARTA,KOTA ADM. JAKARTA TIMUR,CAKUNG,JATINEGARA,...,216.0,19412.0,17.0,81.0,NaN,27146.0,818.0,7130.0,13.0,NaN
82299,1418124,31.0,75.0,6.0,1007.0,3.175061e+09,DKI JAKARTA,KOTA ADM. JAKARTA TIMUR,CAKUNG,CAKUNG BARAT,...,109.0,12950.0,10.0,79.0,2.0,19883.0,571.0,5887.0,8.0,NaN

In [53]:
jabar_df = df[df['nama_prop']=="JAWA BARAT"]

In [54]:
jabar_df

,objectid,no_prop,no_kab,no_kec,no_kel,kode_desa_spatial,nama_prop,nama_kab,nama_kec,nama_kel,...,pensiunan,mengurus_rumah_tangga,perdagangan,perawat,nelayan,pelajar_mahasiswa,guru,wiraswasta,pengacara,lainnya
122,1335947,32.0,5.0,20.0,2007.0,3.205202e+09,JAWA BARAT,KAB. GARUT,CISURUPAN,BALEWANGI,...,36.0,1296.0,51.0,5.0,NaN,1053.0,34.0,542.0,NaN,NaN
198,1336023,32.0,7.0,3.0,2003.0,3.207032e+09,JAWA BARAT,KAB. CIAMIS,CIJEUNGJING,BOJONGMENGGER,...,109.0,1832.0,2.0,6.0,1.0,538.0,29.0,582.0,NaN,NaN
207,1336032,32.0,7.0,10.0,2013.0,3.207102e+09,JAWA BARAT,KAB. CIAMIS,PANAWANGAN,BANGUNJAYA,...,13.0,556.0,4.0,NaN,NaN,111.0,7.0,212.0,NaN,NaN
265,1336090,32.0,7.0,11.0,2013.0,3.207112e+09,JAWA BARAT,KAB. CIAMIS,CIPAKU,SUKAWENING,...,3.0,1032.0,147.0,1.0,1.0,140.0,7.0,238.0,NaN,NaN
415,1336240,32.0,7.0,12.0,2004.0,3.207122e+09,JAWA BARAT,KAB. CIAMIS,JATINAGARA,DAYEUHLUHUR,...,22.0,1547.0,55.0,1.0,NaN,76.0,13.0,755.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83287,1419112,32.0,14.0,14.0,2009.0,3.214142e+09,JAWA BARAT,KAB. PURWAKARTA,CIBATU,WANAWALI,...,6.0,538.0,NaN,1.0,NaN,200.0,14.0,188.0,NaN,NaN
83288,1419113,32.0,14.0,16.0,2009.0,3.214162e+09,JAWA BARAT,KAB. PURWAKARTA,PONDOKSALAM,GURUDUG,...,1.0,888.0,2.0,NaN,NaN,424.0,4.0,268.0,NaN,NaN
83289,1419114,32.0,16.0,8.0,2005.0,3.216082e+09,JAWA BARAT,KAB. BEKASI,CIKARANG BARAT,GANDAMEKAR,...,2.0,1134.0,15.0,1.0,1.0,1035.0,10.0,469.0,NaN,NaN
83290,1419115,32.0,16.0,8.0,2007.0,3.216082e+09,JAWA BARAT,KAB. BEKASI,CIKARANG BARAT,SUKADANAU,...,47.0,6191.0,64.0,10.0,NaN,5984.0,143.0,2686.0,NaN,NaN
83291,1419116,32.0,16.0,1.0,2002.0,3.216012e+09,JAWA BARAT,KAB. BEKASI,TARUMAJAYA,SEGARAJAYA,...,13.0,4759.0,51.0,9.0,257.0,3273.0,141.0,2008.0,NaN,NaN

In [55]:
df['nama_prop'].unique()

array(['JAWA TENGAH', 'ACEH', 'SULAWESI SELATAN', 'JAWA TIMUR',
       'SUMATERA UTARA', 'PAPUA PEGUNUNGAN', 'RIAU', 'SUMATERA BARAT',
       'SULAWESI TENGGARA', 'PAPUA', nan, 'JAWA BARAT', 'SULAWESI UTARA',
       'SULAWESI TENGAH', 'LAMPUNG', 'BANTEN', 'NUSA TENGGARA TIMUR',
       'PAPUA TENGAH', 'PAPUA BARAT DAYA', 'PAPUA BARAT',
       'KALIMANTAN BARAT', 'GORONTALO', 'NUSA TENGGARA BARAT',
       'PAPUA SELATAN', 'JAMBI', 'KALIMANTAN TIMUR', 'SUMATERA SELATAN',
       'MALUKU', 'KALIMANTAN SELATAN', 'SULAWESI BARAT', 'BENGKULU',
       'KALIMANTAN TENGAH', 'BALI', 'MALUKU UTARA', 'KALIMANTAN UTARA',
       'DAERAH ISTIMEWA YOGYAKARTA', 'DKI JAKARTA', 'KEPULAUAN RIAU',
       'KEPULAUAN BANGKA BELITUNG'], dtype=object)